#--------------------------------------------------------------------
# Copyright (c) 2021 James O. D. Hunt <jamesodhunt@gmail.com>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#--------------------------------------------------------------------

name: Build procenv in GitHub Actions build environment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y \
            autoconf \
            autoconf-archive \
            automake \
            autopoint \
            build-essential \
            check \
            clang

      - name: Build with ${{ matrix.compiler }}
        run: |
          ./autogen.sh
          ./configure
          ${{ matrix.compiler }} --version
          make CC=${{ matrix.compiler }} -j$(nproc)

      - name: Test (${{ matrix.compiler }} binary)
        run: |
          make check

      - name: View logs
        run: |
          find . -type f -name "*.log" | while read logfile
          do
            echo -e "INFO: logfile: '$logfile':\n"
            cat "$logfile"
          done

